name: riverpod_seminar
description: "A new Flutter project."

# publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flex_color_scheme: ^7.3.1
  flutter_riverpod: ^2.5.1
  dio: ^5.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: fontApp
      fonts:
        - asset: assets\fonts\PTSerif-Bold.ttf
